from .alligator import Alligator
from .camel import Camel
from .deer import Deer
from .donkey import Donkey
from .elephant import Elephant
from .fox import Fox
from .goat import Goat
from .llama import Llama
from .raccoon import Raccoon
from .sheep import Sheep
from .tiger import Tiger
