from .alligator import Alligator
from .animal import Animal
from .camel import Camel
from .deer import Deer
from .donkey import Donkey
from .eel import Eel
from .elephant import Elephant
from .fish import Fish
from .fox import Fox
from .goat import Goat
from .goose import Goose
from .llama import Llama
from .raccoon import Raccoon
from .shark import Shark
from .sheep import Sheep
from .snake import Snake
from .tiger import Tiger